// Mock company data with locations around the world
const companiesData = [
    {
        id: 1,
        name: "TechCorp Industries",
        country: "United States",
        city: "San Francisco",
        latitude: 37.7749,
        longitude: -122.4194,
        description: "Leading cloud infrastructure and AI solutions provider serving Fortune 500 companies.",
        website: "https://www.techcorp.com",
        employees: 15000,
        founded: 2010,
        revenueRange: "$2.5B - $3B",
        bubbleColor: "bubble-bg-1"
    },
    {
        id: 2,
        name: "GlobalFinance Solutions",
        country: "United Kingdom",
        city: "London",
        latitude: 51.5074,
        longitude: -0.1278,
        description: "Innovative fintech platform revolutionizing digital banking and payments globally.",
        website: "https://www.globalfinance.co.uk",
        employees: 8500,
        founded: 2015,
        revenueRange: "$800M - $1B",
        bubbleColor: "bubble-bg-2"
    },
    {
        id: 3,
        name: "EuroData Systems",
        country: "Germany",
        city: "Berlin",
        latitude: 52.5200,
        longitude: 13.4050,
        description: "European data analytics pioneer providing enterprise intelligence solutions.",
        website: "https://www.eurodatasystems.de",
        employees: 5200,
        founded: 2012,
        revenueRange: "$450M - $550M",
        bubbleColor: "bubble-bg-3"
    },
    {
        id: 4,
        name: "AsiaTech Ventures",
        country: "Singapore",
        city: "Singapore",
        latitude: 1.3521,
        longitude: 103.8198,
        description: "Southeast Asian tech hub connecting startups with investment opportunities.",
        website: "https://www.asiatechventures.sg",
        employees: 3200,
        founded: 2018,
        revenueRange: "$250M - $350M",
        bubbleColor: "bubble-bg-4"
    },
    {
        id: 5,
        name: "BrazilTech Innovation",
        country: "Brazil",
        city: "São Paulo",
        latitude: -23.5505,
        longitude: -46.6333,
        description: "Brazilian tech innovation leader in mobile development and e-commerce solutions.",
        website: "https://www.brasiltech.br",
        employees: 4100,
        founded: 2016,
        revenueRange: "$380M - $450M",
        bubbleColor: "bubble-bg-5"
    },
    {
        id: 6,
        name: "MidEast Digital Hub",
        country: "United Arab Emirates",
        city: "Dubai",
        latitude: 25.2048,
        longitude: 55.2708,
        description: "Regional digital transformation hub serving Middle Eastern enterprises.",
        website: "https://www.mideastdigital.ae",
        employees: 2800,
        founded: 2017,
        revenueRange: "$200M - $280M",
        bubbleColor: "bubble-bg-6"
    },
    {
        id: 7,
        name: "CanadaSoft Development",
        country: "Canada",
        city: "Toronto",
        latitude: 43.6629,
        longitude: -79.3957,
        description: "Canadian software development studio creating enterprise and consumer applications.",
        website: "https://www.canadasoft.ca",
        employees: 2400,
        founded: 2014,
        revenueRange: "$180M - $250M",
        bubbleColor: "bubble-bg-7"
    },
    {
        id: 8,
        name: "DownUnder Tech",
        country: "Australia",
        city: "Sydney",
        latitude: -33.8688,
        longitude: 151.2093,
        description: "Australian technology powerhouse in robotics, IoT, and autonomous systems.",
        website: "https://www.downundertech.au",
        employees: 3600,
        founded: 2013,
        revenueRange: "$320M - $400M",
        bubbleColor: "bubble-bg-8"
    }
];